First fixes 131
INCATools/ontology-development-kit pull request #570
Opened 2022-03-07 10:51 UTC by matentzn

2022-05-02 09:46 UTC, matentzn commented
@gouttegd sorry I bundled a few things into one PR while I was working on many problems at once.. Would like to merge this to return to a more.. atomic form of PRs.. :) Would you mind taking a look?

2022-05-03 10:05 UTC, gouttegd requested changes
Looks good to me, modulo the fact that `js2cli` should be declared in `requirements.txt.lite` _and_ in `requirements.txt`.

2022-05-03 10:52 UTC, matentzn commented on requirements.txt.lite
> +j2cli
I assume you mean `requirements.txt.full`?

2022-05-03 10:58 UTC, gouttegd commented on requirements.txt.lite
> +j2cli
Yes, my bad.

2022-05-03 11:00 UTC, matentzn commented
Else is fine, can I merge?

2022-05-03 11:01 UTC, gouttegd approved these changes

2022-05-03 11:05 UTC, merged