added components doc
INCATools/ontology-development-kit pull request #577
Opened 2022-03-16 16:56 UTC by shawntanzk

2022-03-16 22:07 UTC, matentzn requested changes

2022-03-16 22:07 UTC, matentzn commented on template/_dynamic_files.jinja2
> +	$(ROBOT) annotate -I $(YOUR_COMPONENT_NAME) --ontology-iri $(ONTBASE)/$@ -o $@
This example is confusing, just add a simple working example instead.

2022-03-17 14:18 UTC, shawntanzk commented
> This example is confusing, just add a simple working example instead.

Changed it to just use ROBOT template since that worked clearly with Ray

2022-04-07 18:26 UTC, matentzn approved these changes

2022-04-07 18:26 UTC, merged